# Generated by Django 6.0.1 on 2026-01-19 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='dateInteraction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='typeInteraction',
            field=models.CharField(choices=[('APPEL', 'Appel Téléphonique'), ('EMAIL', 'Email'), ('REUNION', 'Réunion'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
